//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt_18._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalaryEntities1 : DbContext
    {
        public SalaryEntities1()
            : base("name=SalaryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonthlySalary> MonthlySalaries { get; set; }
        private static SalaryEntities1 context;
        public static SalaryEntities1 GetContext()
        {
            if (context == null)
            {
                context = new SalaryEntities1();
            }
            return context;
        }
    }
}
