//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakt_18._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySalary
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Workshop { get; set; }
        public System.DateTime Date { get; set; }
        public decimal SizeSalary { get; set; }
        public byte WorkExperiance { get; set; }
        public byte Category { get; set; }
        public string Position { get; set; }
    }
}
